name: Cross-Platform Release

on:
  push:
    tags:
      - 'v*'  # 仅打 tag 时触发

jobs:
  build:
    # runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            ext: ""
            archive: tar.gz
          - target: x86_64-apple-darwin
            os: macos-latest
            ext: ""
            archive: tar.gz
          - target: x86_64-pc-windows-gnu
            os: windows-latest
            ext: .exe
            archive: zip

    name: Build for ${{ matrix.target }}
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true          # 覆盖默认 Rust 版本

      - name: Install build dependencies (Windows only)
        if: matrix.os == 'windows-latest'
        run: |
          rustup target add ${{ matrix.target }}

      - name: Build binary
        run: cargo build --release --target ${{ matrix.target }}

      - name: Package binary
        run: |
          cd target/${{ matrix.target }}/release
          BINARY_NAME=your_binary_name${{ matrix.ext }}
          ARCHIVE_NAME=${{ matrix.target }}.${{ matrix.archive }}
          mv your_binary_name${{ matrix.ext }} $BINARY_NAME

          if [ "${{ matrix.archive }}" == "zip" ]; then
            zip $ARCHIVE_NAME $BINARY_NAME
          else
            tar czf $ARCHIVE_NAME $BINARY_NAME
          fi

          mv $ARCHIVE_NAME ../../../
        shell: bash

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            target/${{ matrix.target }}.tar.gz
            target/${{ matrix.target }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
