name: Cross-Platform Release

on:
  push:
    tags:
      - 'v*'  # 只有推送 tag 时触发

jobs:
  build:
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            ext: ""
            archive: tar.gz
          - target: x86_64-apple-darwin
            os: macos-latest
            ext: ""
            archive: tar.gz
          - target: x86_64-pc-windows-gnu
            os: windows-latest
            ext: .exe
            archive: zip

    name: Build for ${{ matrix.target }}
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - name: Build binary
        run: cargo build --release --target ${{ matrix.target }}

      - name: List built files (Linux/macOS)
        if: matrix.os != 'windows-latest'
        run: ls -lh target/${{ matrix.target }}/release
        shell: bash

      - name: List built files (Windows)
        if: matrix.os == 'windows-latest'
        run: Get-ChildItem target\x86_64-pc-windows-gnu\release

      - name: Package binary (Unix)
        if: matrix.os != 'windows-latest'
        shell: bash
        run: |
          cd target/${{ matrix.target }}/release
          ARCHIVE_NAME=get-request-info-rs-${{ matrix.target }}.tar.gz
          BINARY_NAME=get-request-info-rs

          tar czf ../../$ARCHIVE_NAME $BINARY_NAME

      - name: Package binary (Windows)
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          $binaryName = "get-request-info-rs.exe"
          $archiveName = "get-request-info-rs-${{ matrix.target }}.zip"
          $binaryPath = "target\\${{ matrix.target }}\\release\\$binaryName"
          $outputPath = "target\\$archiveName"
          Compress-Archive -Path $binaryPath -DestinationPath $outputPath


      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            target/get-request-info-rs-x86_64-unknown-linux-gnu.tar.gz
            target/get-request-info-rs-x86_64-apple-darwin.tar.gz
            target/get-request-info-rs-x86_64-pc-windows-gnu.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
